CREATE TABLE [dbo].[Projektkarta_Enkat](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[Question] [NVARCHAR](500) NULL,
	[value] [NVARCHAR](MAX) NULL,
	[X] [NVARCHAR](50) NULL,
	[Y] [NVARCHAR](50) NULL,
	[UserID] [NVARCHAR](50) NULL,
	[Show] [INT] NULL,
	[AdminActionDate] [NVARCHAR](50) NULL,
	[Stadsdel] [NVARCHAR](100) NULL,
	[Anmald] [NVARCHAR](50) NULL,
	[Stats_kategori] [NVARCHAR](300) NULL,
	[Created] [NVARCHAR](50) NULL,
 CONSTRAINT [PK_Projektkarta_Enkat] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO