CREATE TABLE [dbo].[Projektkartan_AutoHideWords](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[Ord] [NVARCHAR](100) NULL,
	[Created] [NVARCHAR](50) NULL,
 CONSTRAINT [PK_Projektkartan_AutoHideWords] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO